# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='acritcle',
            name='content_text',
            field=models.CharField(default='', max_length=200, verbose_name='文章描述'),
        ),
    ]
