# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171127_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='course',
        ),
    ]
